### ISSUE TITLE
zephyr 环境安装小计

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#406]

**Comment by supperthomas** [comment]
ubuntu 22.04  https://ubuntu.com/download

**Comment by supperthomas** [comment]
![图片](https://user-images.githubusercontent.com/60349489/195857270-33e98868-4cc4-4d38-a0fa-d83b0f55d753.png)

**Comment by supperthomas** [comment]
developer.nordicsemi.com

**Comment by supperthomas** [comment]
```
apt-get update
apt-get upgrade

```

```
sudo apt install --no-install-recommends git cmake ninja-build gperf \
  ccache dfu-util device-tree-compiler wget \
  python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
  make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
```

**Comment by supperthomas** [comment]
west flash --runner jlink

**Comment by supperthomas** [comment]
west build -t menuconfig

**Comment by supperthomas** [comment]
source ~/zephyrproject/.venv/bin/activate

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s/KSNye-nu5DYP2l5c2xOyjQ

**Comment by supperthomas** [comment]
v1.9.1

**Comment by supperthomas** [comment]
- [Bluetooth: Beacon](https://docs.zephyrproject.org/latest/samples/bluetooth/beacon/README.html)  这个52832 52840 都可以跑
- [Bluetooth: Broadcaster](https://docs.zephyrproject.org/latest/samples/bluetooth/broadcaster/README.html)  这个都不能跑  TODO
- [Bluetooth: Broadcast Audio Sink](https://docs.zephyrproject.org/latest/samples/bluetooth/broadcast_audio_sink/README.html)
[Bluetooth: Broadcast Audio Source](https://docs.zephyrproject.org/latest/samples/bluetooth/broadcast_audio_source/README.html)   这两个不知道怎么用
- [Bluetooth: Multiple Broadcaster](https://docs.zephyrproject.org/latest/samples/bluetooth/broadcaster_multiple/README.html) 打出多个广播

**Comment by supperthomas** [comment]
一个比较老的文档：
https://github.com/tidyjiang8/zephyr-inside

**Comment by supperthomas** [comment]
https://openeuler.gitee.io/zephyr-cn/develop/windows.html

**Comment by supperthomas** [comment]
【ZephyrOs-哔哩哔哩】 https://b23.tv/p56CuEf

**Comment by supperthomas** [comment]
https://m.youtube.com/watch?v=v6kUPnKs4TU&list=PLbzoR-pLrL6rQLZttVSF_DwzncObtwyM3


视频介绍

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s/V9ffxh6rca4AufoAqtUEqQ
会议

**Comment by supperthomas** [comment]
加速方法：
1. git 镜像加速
2. west.yml里面hal可以都删了
    - name: hal_nordic
      revision: cf6e9fc5f7c2c98df26f2a4227a95df9a50823e7
      path: modules/hal/nordic
      groups:
        - hal
    - name: hal_nxp
      revision: 1a55ccfde649a97df74a8853cbd9787ddd34bfc4
      path: modules/hal/nxp
      groups:
        - hal
    - name: hal_stm32
      revision: 1bc72c299d0365c0ee2575a97918b22df0899e10
      path: modules/hal/stm32
      groups:
        - hal

**Comment by supperthomas** [comment]
bsim 跑蓝牙模拟器才需要，其他不需要

**Comment by supperthomas** [comment]
最小系统
```
manifest:

  defaults:

    remote: upstream



  remotes:

    - name: upstream

      url-base: https://github.com/zephyrproject-rtos

    - name: babblesim

      url-base: https://github.com/BabbleSim



  group-filter: [-babblesim]



  #

  # Please add items below based on alphabetical order

  projects:

    - name: cmsis

      revision: 74981bf893e8b10931464b9945e2143d99a3f0a3

      path: modules/hal/cmsis

      groups:

        - hal

    - name: hal_stm32

      revision: 1bc72c299d0365c0ee2575a97918b22df0899e10

      path: modules/hal/stm32

      groups:

        - hal



  self:

    path: zephyr

    west-commands: scripts/west-commands.yml

    import: submanifests


```
